// ---------------------------------------------------------------------------
// Deterministic builders for everything a crawler or an answer engine reads:
// the page <head>, robots.txt, llms.txt and sitemap.xml.
//
// None of this is generated by a model. A malformed JSON-LD node or a robots.txt
// with a stray line is worse than none at all, and a language model cannot
// promise well-formed output. AI only ever drafts prose (see drafts.ts); the
// structure around that prose is built here, by hand, and is testable.
// ---------------------------------------------------------------------------

import type { SeoEntityType, SeoFaqPair, SeoSubject } from "./scoring.js";

// The crawlers that feed answer engines. Naming them explicitly is the point:
// a bare `User-agent: *` leaves it ambiguous whether AI training and retrieval
// are welcome, and several of these bots look for their own name first.
export const AI_CRAWLERS: readonly string[] = [
  "GPTBot",
  "OAI-SearchBot",
  "ChatGPT-User",
  "ClaudeBot",
  "Claude-User",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "Google-Extended",
  "GoogleOther",
  "Applebot",
  "Applebot-Extended",
  "Amazonbot",
  "Bytespider",
  "CCBot",
  "cohere-ai",
  "Diffbot",
  "FacebookBot",
  "meta-externalagent",
  "YouBot",
  "Timpibot",
  "Meltwater",
  "Seekr",
  "Scrapy",
  "ImagesiftBot",
  "Omgilibot",
  "DuckAssistBot",
];

/** Matches a crawler or social unfurler that will never run our JavaScript. */
export const CRAWLER_UA = new RegExp(
  [
    ...AI_CRAWLERS,
    "Googlebot",
    "bingbot",
    "Slurp",
    "DuckDuckBot",
    "Baiduspider",
    "YandexBot",
    "Twitterbot",
    "facebookexternalhit",
    "LinkedInBot",
    "Slackbot",
    "TelegramBot",
    "WhatsApp",
    "Discordbot",
    "KAKAOTALK",
    "NaverBot",
    "Yeti",
  ].join("|"),
  "i",
);

export function isCrawlerUserAgent(userAgent: string | undefined | null): boolean {
  if (!userAgent) return false;
  return CRAWLER_UA.test(userAgent);
}

// ── Escaping ───────────────────────────────────────────────────────────────

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** JSON-LD sits inside a <script>, so the one dangerous sequence is `</`. */
function escapeJsonLd(value: string): string {
  return value.replace(/<\//g, "<\\/");
}

function trimTrailingSlash(value: string): string {
  return value.replace(/\/+$/, "");
}

function nonEmpty(value: string | null | undefined): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

// ── <head> ─────────────────────────────────────────────────────────────────

export interface SeoHeadInput {
  subject: SeoSubject;
  /** Absolute origin, e.g. https://metheim-web.vercel.app */
  origin: string;
  /** Path the page is served at, leading slash included. */
  path: string;
  brandName: string;
  siteLabel: string;
  /** seo_defaults.organizationSchema, if the site has one. */
  organizationSchema: Record<string, unknown> | null;
  /** Locales this entity is published in, for the alternate links. */
  alternateLocales: string[];
}

export interface SeoHeadResult {
  title: string;
  description: string | null;
  canonical: string;
  robots: string;
  og: Record<string, string>;
  twitter: Record<string, string>;
  jsonLd: Record<string, unknown>[];
  alternates: { locale: string; href: string }[];
}

function absoluteUrl(origin: string, path: string): string {
  const base = trimTrailingSlash(origin);
  if (!path || path === "/") return base + "/";
  return base + (path.startsWith("/") ? path : `/${path}`);
}

/**
 * Everything a crawler should see for one entity at one locale. An authored
 * seo_title is used verbatim — staff who write a title have already decided how
 * it reads; only the plain page name gets the brand suffix.
 */
export function buildSeoHead(input: SeoHeadInput): SeoHeadResult {
  const { subject, brandName } = input;
  const authored = nonEmpty(subject.seoTitle);
  const plain = nonEmpty(subject.title);
  const title = authored ?? (plain ? `${plain} — ${brandName}` : brandName);

  const description = nonEmpty(subject.seoDescription) ?? nonEmpty(subject.geoAnswerSummary);
  const canonical = nonEmpty(subject.canonicalUrl) ?? absoluteUrl(input.origin, input.path);
  const robots = nonEmpty(subject.robotsDirectives) ?? "index,follow";
  const image = nonEmpty(subject.seoImageUrl);

  const og: Record<string, string> = {
    "og:type": subject.entityType === "blog" ? "article" : "website",
    "og:site_name": input.siteLabel,
    "og:title": nonEmpty(subject.ogTitle) ?? title,
    "og:url": canonical,
    "og:locale": subject.locale,
  };
  const ogDescription = nonEmpty(subject.ogDescription) ?? description;
  if (ogDescription) og["og:description"] = ogDescription;
  if (image) og["og:image"] = image;

  const twitter: Record<string, string> = {
    "twitter:card": image ? "summary_large_image" : "summary",
    "twitter:title": og["og:title"]!,
  };
  if (ogDescription) twitter["twitter:description"] = ogDescription;
  if (image) twitter["twitter:image"] = image;

  return {
    title,
    description,
    canonical,
    robots,
    og,
    twitter,
    jsonLd: buildJsonLd({ ...input, title, description, canonical, image }),
    alternates: input.alternateLocales.map((locale) => ({
      locale,
      href: `${canonical}${canonical.includes("?") ? "&" : "?"}lang=${locale}`,
    })),
  };
}

function baseSchemaType(entityType: SeoEntityType): string {
  if (entityType === "blog") return "Article";
  if (entityType === "listing") return "Product";
  return "WebPage";
}

/**
 * An explicit `json_ld` on the entity wins outright — staff who hand-wrote a
 * schema node meant it. Otherwise we generate a baseline node, plus FAQPage
 * when there are pairs, plus the site's Organization.
 */
function buildJsonLd(
  input: SeoHeadInput & {
    title: string;
    description: string | null;
    canonical: string;
    image: string | null;
  },
): Record<string, unknown>[] {
  const nodes: Record<string, unknown>[] = [];
  const override = input.subject.jsonLd;

  if (override && typeof override === "object" && Object.keys(override as object).length > 0) {
    if (Array.isArray(override)) nodes.push(...(override as Record<string, unknown>[]));
    else nodes.push(override as Record<string, unknown>);
  } else {
    const node: Record<string, unknown> = {
      "@context": "https://schema.org",
      "@type": baseSchemaType(input.subject.entityType),
      name: input.title,
      url: input.canonical,
      inLanguage: input.subject.locale,
    };
    if (input.description) node["description"] = input.description;
    if (input.image) node["image"] = input.image;
    if (input.subject.entityType === "blog") {
      node["headline"] = input.title;
      if (input.subject.updatedAt) {
        const date =
          input.subject.updatedAt instanceof Date
            ? input.subject.updatedAt
            : new Date(input.subject.updatedAt);
        if (!Number.isNaN(date.getTime())) node["dateModified"] = date.toISOString();
      }
    }
    nodes.push(node);
  }

  const faq = (input.subject.geoFaq ?? []).filter(
    (pair): pair is SeoFaqPair => Boolean(pair?.q?.trim() && pair?.a?.trim()),
  );
  if (faq.length > 0) {
    nodes.push({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: faq.map((pair) => ({
        "@type": "Question",
        name: pair.q.trim(),
        acceptedAnswer: { "@type": "Answer", text: pair.a.trim() },
      })),
    });
  }

  if (input.organizationSchema && Object.keys(input.organizationSchema).length > 0) {
    nodes.push({
      "@context": "https://schema.org",
      "@type": "Organization",
      ...input.organizationSchema,
    });
  }

  return nodes;
}

/**
 * A complete HTML document for a crawler that will not run JavaScript. The body
 * carries the answer summary and FAQ as real text, because an answer engine can
 * only quote what it can read.
 */
export function renderCrawlerHtml(head: SeoHeadResult, subject: SeoSubject, bodyText: string): string {
  const lines: string[] = [
    "<!doctype html>",
    `<html lang="${escapeHtml(subject.locale)}">`,
    "<head>",
    '<meta charset="utf-8">',
    `<title>${escapeHtml(head.title)}</title>`,
    `<meta name="robots" content="${escapeHtml(head.robots)}">`,
    `<link rel="canonical" href="${escapeHtml(head.canonical)}">`,
  ];
  if (head.description) {
    lines.push(`<meta name="description" content="${escapeHtml(head.description)}">`);
  }
  if (subject.seoKeywords) {
    lines.push(`<meta name="keywords" content="${escapeHtml(subject.seoKeywords)}">`);
  }
  for (const [key, value] of Object.entries(head.og)) {
    lines.push(`<meta property="${escapeHtml(key)}" content="${escapeHtml(value)}">`);
  }
  for (const [key, value] of Object.entries(head.twitter)) {
    lines.push(`<meta name="${escapeHtml(key)}" content="${escapeHtml(value)}">`);
  }
  for (const alternate of head.alternates) {
    lines.push(
      `<link rel="alternate" hreflang="${escapeHtml(alternate.locale)}" href="${escapeHtml(alternate.href)}">`,
    );
  }
  for (const node of head.jsonLd) {
    lines.push(
      `<script type="application/ld+json">${escapeJsonLd(JSON.stringify(node))}</script>`,
    );
  }
  lines.push("</head>", "<body>");
  lines.push(`<h1>${escapeHtml(head.title)}</h1>`);
  if (subject.geoAnswerSummary?.trim()) {
    lines.push(`<p>${escapeHtml(subject.geoAnswerSummary.trim())}</p>`);
  } else if (head.description) {
    lines.push(`<p>${escapeHtml(head.description)}</p>`);
  }
  const faq = (subject.geoFaq ?? []).filter((pair) => pair?.q?.trim() && pair?.a?.trim());
  if (faq.length > 0) {
    lines.push("<section>");
    for (const pair of faq) {
      lines.push(`<h2>${escapeHtml(pair.q.trim())}</h2>`, `<p>${escapeHtml(pair.a.trim())}</p>`);
    }
    lines.push("</section>");
  }
  if (bodyText.trim()) lines.push(`<div>${escapeHtml(bodyText.trim())}</div>`);
  lines.push(`<p><a href="${escapeHtml(head.canonical)}">${escapeHtml(head.canonical)}</a></p>`);
  lines.push("</body>", "</html>");
  return lines.join("\n");
}

// ── robots.txt ─────────────────────────────────────────────────────────────

/**
 * Every AI crawler named and allowed, then the catch-all, then the sitemap.
 * `extra` is the site's own seo_defaults.robotsExtra, appended verbatim so an
 * operator can add a Disallow without editing code.
 */
export function buildRobotsTxt(origin: string, extra?: string | null): string {
  const base = trimTrailingSlash(origin);
  const lines: string[] = [
    "# Search and answer engines are both welcome here.",
    "# The AI crawlers are named explicitly: several of them look for their own",
    "# user-agent before falling back to *, and an ambiguous file gets read as a",
    "# refusal. Generated by the API — edit under CMS → SEO · GEO, not by hand.",
    "",
  ];
  for (const bot of AI_CRAWLERS) {
    lines.push(`User-agent: ${bot}`, "Allow: /", "");
  }
  lines.push("User-agent: *", "Allow: /", "");
  const trimmedExtra = nonEmpty(extra);
  if (trimmedExtra) lines.push(trimmedExtra, "");
  lines.push(`Sitemap: ${base}/sitemap.xml`, `# Curated index: ${base}/llms.txt`, "");
  return lines.join("\n");
}

// ── llms.txt ───────────────────────────────────────────────────────────────

export interface LlmsSection {
  heading: string;
  entries: { title: string; url: string; note?: string | null }[];
}

/**
 * A curated markdown index for answer engines: what this site is, and the pages
 * worth reading, in priority order. Deliberately short — its value is that it
 * is hand-picked, not that it lists everything (that is what sitemap.xml is).
 */
export function buildLlmsTxt(
  siteLabel: string,
  intro: string | null | undefined,
  sections: LlmsSection[],
): string {
  const lines: string[] = [`# ${siteLabel}`, ""];
  const trimmedIntro = nonEmpty(intro);
  if (trimmedIntro) lines.push(`> ${trimmedIntro}`, "");
  for (const section of sections) {
    if (section.entries.length === 0) continue;
    lines.push(`## ${section.heading}`, "");
    for (const entry of section.entries) {
      const note = nonEmpty(entry.note);
      lines.push(`- [${entry.title}](${entry.url})${note ? `: ${note}` : ""}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

// ── sitemap.xml ────────────────────────────────────────────────────────────

export interface SitemapEntry {
  path: string;
  updatedAt?: Date | string | null;
  /** Locales with a published translation, rendered as xhtml:link alternates. */
  locales?: string[];
}

export function buildSitemapXml(origin: string, entries: SitemapEntry[]): string {
  const base = trimTrailingSlash(origin);
  const lines: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" ' +
      'xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ];
  for (const entry of entries) {
    const loc = absoluteUrl(base, entry.path);
    lines.push("  <url>", `    <loc>${escapeXml(loc)}</loc>`);
    if (entry.updatedAt) {
      const date = entry.updatedAt instanceof Date ? entry.updatedAt : new Date(entry.updatedAt);
      if (!Number.isNaN(date.getTime())) {
        lines.push(`    <lastmod>${date.toISOString().slice(0, 10)}</lastmod>`);
      }
    }
    for (const locale of entry.locales ?? []) {
      const href = `${loc}${loc.includes("?") ? "&" : "?"}lang=${locale}`;
      lines.push(
        `    <xhtml:link rel="alternate" hreflang="${escapeXml(locale)}" href="${escapeXml(href)}"/>`,
      );
    }
    lines.push("  </url>");
  }
  lines.push("</urlset>", "");
  return lines.join("\n");
}
