import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import productCatalogRouter from "./product-catalog";
import contractTypesRouter from "./contract-types";
import productGroupsRouter from "./product-groups";
import productTypesRouter from "./product-types";
import chartOfAccountsRouter from "./chart-of-accounts";
import rentalFeeSchedulesRouter from "./rental-fee-schedules";
import reportsRouter from "./reports";
import suburbsRouter from "./suburbs";
import propertiesRouter from "./properties";
import spaceOptionsRouter from "./space-options";
import spacePoliciesRouter from "./space-policies";
import spacesRouter from "./spaces";
import commissionsRouter from "./commissions";
import paymentInfoRouter from "./payment-info";
import contactsRouter from "./contacts";
import accountsRouter from "./accounts";
import lookupRouter from "./lookup";
import tasksRouter from "./tasks";
import leadsRouter from "./leads";
import serviceHostsRouter from "./service-hosts";
import bookingsRouter from "./bookings";
import productsRouter from "./products";
import contractsRouter from "./contracts";
import invoicesRouter from "./invoices";
import workOrdersRouter from "./work-orders";
import calendarRouter from "./calendar";
import systemLogsRouter from "./system-logs";
import emailTemplatesRouter from "./email-templates";
import emailLogsRouter from "./email-logs";
import recurringSchedulesRouter from "./recurring-schedules";
import stripeRouter from "./stripe";
import integrationsRouter from "./integrations";
import spaceImagesRouter from "./space-images";
import promotionsRouter from "./promotions";
import beneficiariesRouter from "./beneficiaries";
import serviceCatalogRouter from "./service-catalog";
import csTicketsRouter from "./cs-tickets";
import blogPostsRouter from "./blog-posts";
import blogCategoriesRouter from "./blog-categories";
import exchangeRatesRouter from "./exchange-rates";
import translationsRouter from "./translations";
import documentsRouter from "./documents";
import quotesRouter from "./quotes";
import companyInfoRouter from "./company-info";
import otaChannelsRouter from "./ota-channels";
import addonServicesRouter from "./addon-services";
import apiCredentialsRouter from "./api-credentials";
import applicationEmailSettingsRouter from "./application-email-settings";
import { homestayAdminRouter } from "./homestay";
import { homestayStudentAdminRouter } from "./homestay-students";
import { shortTermAdminRouter } from "./short-term";
import { homestayPlacementAdminRouter } from "./homestay-placements";
import { documentTemplatesAdminRouter } from "./document-templates";
import saleListingsRouter from "./sale-listings";
import contentTranslationsRouter from "./content-translations";
import tablePrefsRouter from "./table-prefs";
const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(productCatalogRouter);
router.use(contractTypesRouter);
router.use(productGroupsRouter);
router.use(productTypesRouter);
router.use(chartOfAccountsRouter);
router.use(rentalFeeSchedulesRouter);
router.use(reportsRouter);
router.use(suburbsRouter);
router.use(propertiesRouter);
router.use(spaceOptionsRouter);
router.use(spacePoliciesRouter);
router.use(spacesRouter);
router.use(commissionsRouter);
router.use(paymentInfoRouter);
router.use(contactsRouter);
router.use(accountsRouter);
router.use(lookupRouter);
router.use(tasksRouter);
router.use(leadsRouter);
router.use(serviceHostsRouter);
router.use(bookingsRouter);
router.use(productsRouter);
router.use(contractsRouter);
router.use(invoicesRouter);
router.use(workOrdersRouter);
router.use(calendarRouter);
router.use(systemLogsRouter);
router.use(emailTemplatesRouter);
router.use(emailLogsRouter);
router.use(recurringSchedulesRouter);
router.use(stripeRouter);
router.use(integrationsRouter);
router.use(spaceImagesRouter);
router.use(promotionsRouter);
router.use(beneficiariesRouter);
router.use(serviceCatalogRouter);
router.use(csTicketsRouter);
router.use(blogPostsRouter);
router.use(blogCategoriesRouter);
router.use(exchangeRatesRouter);
router.use(translationsRouter);
router.use(documentsRouter);
router.use(quotesRouter);
router.use(companyInfoRouter);
router.use(otaChannelsRouter);
router.use(addonServicesRouter);
router.use(apiCredentialsRouter);
router.use(applicationEmailSettingsRouter);
router.use(homestayAdminRouter);
router.use(homestayStudentAdminRouter);
router.use(shortTermAdminRouter);
router.use(homestayPlacementAdminRouter);
router.use(documentTemplatesAdminRouter);
router.use(saleListingsRouter);
router.use(contentTranslationsRouter);
router.use(tablePrefsRouter);
// Note: partnerAuthRouter, agentPortalRouter, ownerPortalRouter are registered in app.ts
// BEFORE the requireAuth middleware to allow partner JWT auth to bypass the admin auth guard.

export default router;
