import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import productCatalogRouter from "./product-catalog";
import contractTypesRouter from "./contract-types";
import reportsRouter from "./reports";
import suburbsRouter from "./suburbs";
import propertiesRouter from "./properties";
import spaceOptionsRouter from "./space-options";
import spacePoliciesRouter from "./space-policies";
import spacesRouter from "./spaces";
import commissionsRouter from "./commissions";
import paymentInfoRouter from "./payment-info";
import contactsRouter from "./contacts";
import accountsRouter from "./accounts";
import lookupRouter from "./lookup";
import tasksRouter from "./tasks";
import leadsRouter from "./leads";
import serviceHostsRouter from "./service-hosts";
import bookingsRouter from "./bookings";
import productsRouter from "./products";
import contractsRouter from "./contracts";
import invoicesRouter from "./invoices";
import workOrdersRouter from "./work-orders";
import systemLogsRouter from "./system-logs";
import emailTemplatesRouter from "./email-templates";
import emailLogsRouter from "./email-logs";
import recurringSchedulesRouter from "./recurring-schedules";
import stripeRouter from "./stripe";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(productCatalogRouter);
router.use(contractTypesRouter);
router.use(reportsRouter);
router.use(suburbsRouter);
router.use(propertiesRouter);
router.use(spaceOptionsRouter);
router.use(spacePoliciesRouter);
router.use(spacesRouter);
router.use(commissionsRouter);
router.use(paymentInfoRouter);
router.use(contactsRouter);
router.use(accountsRouter);
router.use(lookupRouter);
router.use(tasksRouter);
router.use(leadsRouter);
router.use(serviceHostsRouter);
router.use(bookingsRouter);
router.use(productsRouter);
router.use(contractsRouter);
router.use(invoicesRouter);
router.use(workOrdersRouter);
router.use(systemLogsRouter);
router.use(emailTemplatesRouter);
router.use(emailLogsRouter);
router.use(recurringSchedulesRouter);
router.use(stripeRouter);

export default router;
