#!/usr/bin/env node
/**
 * generate-brand.mjs — write src/brand.overrides.css from BRAND_* env.
 *
 * White-label build-time brand injection (spec §2.4). Run BEFORE `vite build`
 * for a white-label instance, with the instance's brand env set:
 *
 *   BRAND_ORANGE="256 84% 58%" BRAND_FONT_DISPLAY='"Sora", sans-serif' \
 *     pnpm --filter @workspace/design-tokens generate-brand
 *
 * With no BRAND_* env set it regenerates the empty default (idempotent no-op),
 * so it is safe to run unconditionally in any build pipeline. Overriding a
 * primitive (e.g. --brand-orange) cascades through brand.css's `@theme inline`
 * and each app's `--primary: var(--brand-orange)` with no other change.
 *
 * Values are raw HSL triplets ("H S% L%") to match the shadcn hsl(var(--x))
 * convention — same format as brand.css. Fonts are full CSS font-family stacks.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "brand.overrides.css");

// env var → CSS custom property
const COLOR_TOKENS = {
  BRAND_ORANGE: "--brand-orange",
  BRAND_NAVY: "--brand-navy",
  BRAND_TEAL: "--brand-teal",
  BRAND_CREAM: "--brand-cream",
  BRAND_BURNT: "--brand-burnt",
  BRAND_APRICOT: "--brand-apricot",
  BRAND_INK: "--brand-ink",
  BRAND_WHITE: "--brand-white",
};
const FONT_TOKENS = {
  BRAND_FONT_DISPLAY: "--brand-font-display",
  BRAND_FONT_SANS: "--brand-font-sans",
};

const HSL_TRIPLET = /^\d{1,3}\s+\d{1,3}(?:\.\d+)?%\s+\d{1,3}(?:\.\d+)?%$/;

const lines = [];
for (const [envVar, cssVar] of Object.entries(COLOR_TOKENS)) {
  const raw = process.env[envVar];
  if (!raw) continue;
  const val = raw.trim();
  if (!HSL_TRIPLET.test(val)) {
    console.error(`[generate-brand] ${envVar}="${val}" is not an HSL triplet "H S% L%" — skipped.`);
    continue;
  }
  lines.push(`  ${cssVar}: ${val};`);
}
for (const [envVar, cssVar] of Object.entries(FONT_TOKENS)) {
  const raw = process.env[envVar];
  if (!raw) continue;
  lines.push(`  ${cssVar}: ${raw.trim()};`);
}

const header = `/**
 * Per-instance brand overrides — AUTO-GENERATED by scripts/generate-brand.mjs.
 * Do NOT edit by hand. Regenerate via BRAND_* env. See
 * docs/proposals/WHITELABEL_INSTANCE_SEPARATION.md §2.4.
 */`;

const body = lines.length
  ? `:root {\n${lines.join("\n")}\n}\n`
  : `:root {\n}\n`;

writeFileSync(OUT, `${header}\n${body}`);
console.log(
  lines.length
    ? `[generate-brand] wrote ${lines.length} override(s) to brand.overrides.css`
    : `[generate-brand] no BRAND_* env set — wrote empty default (no-op).`,
);
